Karbashit/GP2_Team05

Team05/Assets/Personal/Andreas/Scripts/Actors/Actor.cs, Team05/Assets/Personal/Joakim/Scenes/CharacterSelection.prefab, Team05/Assets/Personal/Joakim/Scenes/CharacterSelection.prefab.meta, Team05/Assets/Personal/Joakim/Scenes/JK_TestScene.unity, Team05/Assets/Personal/Joakim/Scripts/CharacterManager.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Attack/PlayerAttackScheme.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Personal/Joakim/Scripts/HealthSystem.cs, Team05/Assets/Personal/Joakim/Scripts/PlayerAssignmentRework.meta, Team05/Assets/Personal/Joakim/Scripts/PlayerAssignmentRework/AssignPlayer.cs, Team05/Assets/Personal/Joakim/Scripts/PlayerAssignmentRework/AssignPlayer.cs.meta, Team05/Assets/Personal/Joakim/Scripts/UI/CharacterSelection.cs, Team05/Assets/Resources/Input/PlayerInput.inputactions, Team05/Assets/Resources/Player.prefab, Team05/Assets/Resources/Player1Health.mat, Team05/Assets/Resources/Player1Health.mat.meta, Team05/Assets/Resources/Player1HealthBar.shadergraph, Team05/Assets/Resources/Player1HealthBar.shadergraph.meta, Team05/Assets/Resources/Player2Health.mat, Team05/Assets/Resources/Player2Health.mat.meta, Team05/Assets/Resources/Player2HealthBar.shadergraph, Team05/Assets/Resources/Player2HealthBar.shadergraph.meta
=> HealthSystem wip, HealthShader

Team05/Assets/Personal/Andreas/Scripts/Actors/Actor.cs, Team05/Assets/Personal/Andreas/Scripts/FlowAgentManager.cs.meta, Team05/Assets/Personal/Joakim/Scenes/JK_TestScene.unity, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Personal/Joakim/Scripts/HealthSystem.cs, Team05/Assets/Resources/Player.prefab, Team05/Assets/Resources/Player1Health.mat, Team05/Assets/Resources/Player1HealthBar.shadergraph, Team05/Assets/Resources/Player2Health.mat, Team05/Assets/Resources/Player2HealthBar.shadergraph, Team05/ProjectSettings/TagManager.asset
=> healthsystem works

Team05/Assets/Personal/Andreas/Scripts/FlowAgentManager.cs.meta, Team05/Assets/Personal/Joakim/Prefabs/CharacterSelection.prefab, Team05/Assets/Personal/Joakim/Prefabs/MainGameUi.prefab, Team05/Assets/Personal/Joakim/Prefabs/MainGameUi.prefab.meta
Gonna implement all in main so want it tidyyyyy
=> Prefabs of new or updated systems

Team05/Assets/Personal/Joakim/MainScene_Copy_Joakim.unity, Team05/Assets/Personal/Joakim/Scripts/Attacks/RangedAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Attack/PlayerAttackScheme.cs, Team05/Assets/Personal/Joakim/VFX.meta, Team05/Assets/Personal/Joakim/VFX/BallExplode.shadergraph, Team05/Assets/Personal/Joakim/VFX/BallExplode.shadergraph.meta, Team05/Assets/Personal/Joakim/VFX/BallExplodeFX.prefab, Team05/Assets/Personal/Joakim/VFX/BallExplodeFX.prefab.meta, Team05/Assets/Personal/Joakim/VFX/BallExplodeGraph.vfx, Team05/Assets/Personal/Joakim/VFX/BallExplodeGraph.vfx.meta, Team05/Assets/Personal/Joakim/VFX/LightningStun.shadergraph, Team05/Assets/Personal/Joakim/VFX/LightningStun.shadergraph.meta, Team05/Assets/Personal/Joakim/VFX/LightningStunGraph.prefab, Team05/Assets/Personal/Joakim/VFX/LightningStunGraph.prefab.meta, Team05/Assets/Personal/Joakim/VFX/LightningStunGraph.vfx, Team05/Assets/Personal/Joakim/VFX/LightningStunGraph.vfx.meta, Team05/Assets/Resources/BallExplodeFX.prefab, Team05/Assets/Resources/BallExplodeFX.prefab.meta, Team05/Assets/Resources/Player1Health.mat, Team05/Assets/Resources/Player2Health.mat, Team05/Assets/Resources/RangedSpecialB.prefab, Team05/Assets/Resources/StunBallHitFX.prefab, Team05/Packages/manifest.json, Team05/Packages/packages-lock.json, Team05/ProjectSettings/VFXManager.asset
=> Lightning and Explosion VFX

Team05/Assets/Personal/Joakim/MainScene_Copy_Joakim.unity, Team05/Assets/Personal/Joakim/Scripts/Attacks/RangedAttacks.cs, Team05/Assets/Resources/Player1Health.mat
=> stunball hit fix

Team05/Assets/Personal/Joakim/MainScene_Copy_Joakim.unity, Team05/Assets/Personal/Joakim/Prefabs/ControlsMockup.prefab, Team05/Assets/Personal/Joakim/Prefabs/ControlsMockup.prefab.meta
=> controls ui mockup

Team05/Assets/CheckpointManager.cs, Team05/Assets/CheckpointManager.cs.meta, Team05/Assets/MainScene/MainScene.unity.meta, Team05/Assets/MainScene/MainSceneOld.unity, Team05/Assets/MainScene/MainSceneOld.unity.meta, Team05/Assets/Personal/Andreas/Scenes/MainScene_Test.unity, Team05/Assets/Personal/Andreas/Scripts/Actors/Actor.cs, Team05/Assets/Personal/Andreas/Scripts/Actors/Enemy.cs, Team05/Assets/Personal/Andreas/Scripts/GameManager.cs, Team05/Assets/Personal/Andreas/Scripts/RealRope.cs, Team05/Assets/Personal/Joakim/Scripts/Attacks/MeleeAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/Attacks/RangedAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterManager.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Resources/MeleeHit.prefab, Team05/Assets/Resources/Player.prefab, Team05/Assets/Resources/Player1Health.mat, Team05/Assets/Resources/Player2Health.mat, Team05/Assets/Resources/RangedBasicProjectile.prefab, Team05/ProjectSettings/EditorBuildSettings.asset, Team05/ProjectSettings/Packages/com.unity.probuilder/Settings.json
=> mainlevel stuffs

Team05/Assets/Personal/Joakim/MainScene_Copy_Joakim.unity, Team05/Assets/Personal/Joakim/Scripts/Attacks/MeleeAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/Attacks/RangedAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Attack/PlayerAttackScheme.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Resources/Input/PlayerInput.inputactions
=> Removed X ability, Rebound controls

Team05/Assets/Personal/Andreas/Scripts/GameManager.cs, Team05/Assets/Personal/Joakim/MainScene_Copy_Joakim.unity, Team05/Assets/Personal/Joakim/Scripts/Attacks/Attack.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterManager.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Personal/Johan/Prefabs/UICanvas.prefab, Team05/Assets/Personal/Johan/Prefabs/UICanvas.prefab.meta, Team05/Assets/Personal/Johan/Script/PlayerHudUI.cs
=> Ability Cooldowns UI, CD

Team05/Assets/Personal/Andreas/Scripts/Destructible.cs, Team05/Assets/Personal/Joakim/MainScene_Copy_Joakim.unity, Team05/Assets/PlankFly.cs, Team05/Assets/PlankFly.cs.meta, Team05/Assets/Resources/Plank.prefab, Team05/Assets/Resources/Plank.prefab.meta, Team05/Assets/Resources/brown.mat, Team05/Assets/Resources/brown.mat.meta
=> PLANKS FLY NOW HEHE

Team05/Assets/Personal/Joakim/MainScene_Copy_Joakim.unity, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Attack/PlayerAttackScheme.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Personal/Joakim/Scripts/Mechanics/FuseBoxMultipleCoilsOnly.cs, Team05/Assets/Personal/Joakim/VFX/Shaders/ShieldDome.shadergraph, Team05/Assets/Personal/Joakim/VFX/Shaders/ShieldDomeMat.mat, Team05/Assets/Personal/John/BrankAnimController.controller, Team05/Assets/Personal/John/Josephine/Josephine_AnimController.controller, Team05/Assets/Resources/MeleeShieldDome.prefab, Team05/Assets/Resources/Player.prefab
=> VFX and character walk anim

Team05/Assets/Personal/Joakim/VFX/Shaders/Environment/slime.jpg.meta, Team05/Assets/Resources/RangedSpecialA.prefab
=> spiced prefab

Team05/Assets/MeleeAttackParticle.cs, Team05/Assets/MeleeAttackParticle.cs.meta, Team05/Assets/Personal/Joakim/MainScene_Copy_Joakim.unity, Team05/Assets/Personal/Joakim/Scripts/Attacks/MeleeAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Attack/PlayerAttackScheme.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Personal/Joakim/VFX/VFX/BasicAttacks.meta, Team05/Assets/Personal/Joakim/VFX/VFX/BasicAttacks/MeleeBasic.vfx, Team05/Assets/Personal/Joakim/VFX/VFX/BasicAttacks/MeleeBasic.vfx.meta, Team05/Assets/Personal/John/BrankAnimController.controller, Team05/Assets/Personal/John/Brank_AllAnimationsIDLE.fbx.meta, Team05/Assets/Resources/MeleeHit.prefab, Team05/Assets/Resources/RangedBasicProjectile.prefab
=> Basic attack vfx and other fixes

Team05/Assets/Personal/Andreas/Scripts/Actors/Enemy.cs, Team05/Assets/Personal/Andreas/Scripts/EnemyStuff/EnemyStates/EnemyStateHunt.cs, Team05/Assets/Personal/Joakim/Scripts/Attacks/MeleeAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/Attacks/RangedAttacks.cs, Team05/Assets/Personal/John/enemy/Bosse_AnimController.controller, Team05/Assets/Personal/John/enemy/Gunnar_AnimController 1.controller, Team05/Assets/Resources/Prefabs/Enemies/Bosse.prefab, Team05/Assets/Resources/Prefabs/Enemies/Gunnar.prefab
added, not sure if working cause i dunno how navmesh really works
=> EnemyAnimations

Team05/.gitattributes, Team05/Assets/Personal/Joakim/Scripts/Attacks/RangedAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Attack/PlayerAttackScheme.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Personal/Joakim/Scripts/Mechanics/PowerCoil.cs, Team05/Assets/Resources/RangedSpecialB.prefab
=> remove lfs and stuff

Team05/Assets/Personal/Blair/BB_Animations/BannerAC.controller, Team05/Assets/Personal/Blair/BB_Animations/BannerAC.controller.meta, Team05/Assets/Personal/Blair/BB_Animations/ClothesAC.controller, Team05/Assets/Personal/Blair/BB_Animations/ClothesAC.controller.meta, Team05/Assets/Personal/Blair/BB_Animations/bannerloopTimeline.playable, Team05/Assets/Personal/Blair/BB_Animations/bannerloopTimeline.playable.meta, Team05/Assets/Personal/Blair/BB_Assets/bannerloop.abc.meta, Team05/Assets/Personal/Blair/BB_Materials/TileableMaterials/BB_Tileable_MetalPanelsBare.mat, Team05/Assets/Personal/Blair/BB_Materials/TileableMaterials/BB_Tileable_MetalPanelsPainted.mat, Team05/Assets/Personal/Blair/BB_Prefabs/LoopingBannerPrefab.prefab, Team05/Assets/Personal/Blair/BB_Prefabs/LoopingBannerPrefab.prefab.meta, Team05/Assets/Personal/Blair/BB_Prefabs/LoopingClothesPrefab.prefab
=> Looping Cloth Prefabs

Team05/Assets/Personal/Andreas/Scenes/PonkScene.unity, Team05/Assets/Personal/Andreas/Scenes/RopeScene.unity, Team05/Assets/Personal/Andreas/Scenes/TestScene1.unity, Team05/Assets/Personal/Corentin/LevelDesign.unity, Team05/Assets/Personal/Douglas/CamSwitchers.prefab, Team05/Assets/Personal/Douglas/CamSwitchers.prefab.meta, Team05/Assets/Personal/Douglas/Camera.prefab, Team05/Assets/Personal/Douglas/Camera.prefab.meta, Team05/Assets/Personal/Douglas/CameraDesign 1.unity, Team05/Assets/Personal/Douglas/CameraDesign 1.unity.meta, Team05/Assets/Personal/Douglas/CameraDesign.unity, Team05/Assets/Personal/Douglas/CameraDesign.unity.meta, Team05/Assets/Personal/Joakim/Scenes/JK_TestScene.unity, Team05/Assets/Personal/Johan/UI.unity, Team05/Assets/Personal/John/JohnAnimationTEST.unity, Team05/Assets/Resources/Player1Health.mat
Made the cameras into one prefab and the switches. Added 2 box colliders to the front gate.
=> Changed the Dolly +added colliders to front gate

Team05/Assets/Personal/Blair/BB_Materials/Triplanar/Brick.mat, Team05/Assets/Personal/Blair/BB_Materials/Triplanar/Concrete Large.mat, Team05/Assets/Personal/Blair/BB_Materials/Triplanar/Concrete Large.mat.meta, Team05/Assets/Personal/Blair/BB_Materials/Triplanar/Concrete.mat, Team05/Assets/Personal/Blair/BB_Materials/Triplanar/MetalPanelsBare.mat, Team05/Assets/Personal/Blair/BB_Materials/Triplanar/MetalPanelsPainted.mat
=> texture base

Team05/Assets/Personal/Andreas/Scripts/GameManager.cs, Team05/Assets/Personal/Joakim/Scripts/Attacks/RangedAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Personal/Joakim/Scripts/HealthSystem.cs, Team05/Assets/Personal/Joakim/Scripts/UI/CharacterSelection.cs, Team05/Assets/Resources/Prefabs/Canvases.meta, Team05/Assets/Resources/Prefabs/Canvases/GameOverCanvas.prefab, Team05/Assets/Resources/Prefabs/Canvases/GameOverCanvas.prefab.meta, Team05/Assets/Resources/RangedSpecialA.prefab
=> Death Screen BETA, jose trap bug fixed, etc

Team05/Assets/Personal/Joakim/Scripts/Mechanics/SoundTrigger.cs, Team05/Assets/Personal/Joakim/Scripts/Mechanics/SoundTrigger.cs.meta, Team05/Assets/Resources/Prefabs/Sound.meta, Team05/Assets/Resources/Prefabs/Sound/SoundTrigger.prefab, Team05/Assets/Resources/Prefabs/Sound/SoundTrigger.prefab.meta
=> Sound trigger

Team05/Assets/MainScene/MainScene.unity.meta
=> goodbyemainscene (for now)

Team05/Assets/Personal/Andreas/BlairsChanges.prefab, Team05/Assets/Personal/Andreas/Scripts/GameManager.cs, Team05/Assets/Personal/Andreas/Scripts/HealingZone/HealingZone.cs, Team05/Assets/Personal/Douglas/Camera.prefab, Team05/Assets/Personal/Joakim/Prefabs/CharacterSelection.prefab, Team05/Assets/Personal/Joakim/Scripts/Attacks/RangedAttacks.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterManager.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Attack/PlayerAttackScheme.cs, Team05/Assets/Personal/Joakim/Scripts/CharacterRelated/Player.cs, Team05/Assets/Personal/Joakim/Scripts/HealthSystem.cs, Team05/Assets/Personal/Joakim/Scripts/Mechanics/PowerCoil.cs, Team05/Assets/Personal/Joakim/Scripts/UI/CharacterSelection.cs, Team05/Assets/Personal/John/BrankAnimController.controller, Team05/Assets/Resources/Player1Health.mat, Team05/Assets/Resources/Player1HealthBar.shadergraph, Team05/Assets/Resources/Player2Health.mat, Team05/Assets/Resources/Player2HealthBar.shadergraph, Team05/Assets/Resources/Prefabs/Enemies/Bosse.prefab, Team05/Assets/Resources/Prefabs/Enemies/Gunnar.prefab, Team05/Assets/Resources/Prefabs/Player/Model/Bronk.prefab, Team05/Assets/Resources/Prefabs/Player/Model/Jose.prefab, Team05/Assets/Resources/Prefabs/Player/Player.prefab, Team05/Assets/Resources/RangedSpecialA.prefab, Team05/Assets/Resources/Sound/Music/main_game_music.mp3.meta
=> Bug fixes, quality improvements

Team05/Assets/MainScene/PrefabsLevels/LastRoom.prefab, Team05/Assets/Personal/Andreas/BlairsChanges.prefab, Team05/Assets/Personal/John/FinalWholeRoom 1.prefab, Team05/Assets/Personal/John/Light/lamp02.prefab
Replaced more objects in various level prefabs
=> Replaced more objects in various level prefabs
